# Generated by Django 5.2.8 on 2026-02-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuleiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('resposta_correta', models.CharField(max_length=100)),
                ('opcao_a', models.CharField(max_length=100)),
                ('opcao_b', models.CharField(max_length=100)),
                ('opcao_c', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
    ]
