# Generated by Django 5.2.8 on 2026-02-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuleiro', '0002_pergunta_delete_questao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='perguntas/'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='opcao_d',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='resposta_correta',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
