# Generated by Django 5.2.8 on 2026-02-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuleiro', '0003_pergunta_imagem_pergunta_opcao_d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='nivel',
            field=models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], default='F', max_length=1),
        ),
    ]
